services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app
    restart: unless-stopped
    init: true
    ports:
      - "8080:8080"  # Exposed by Dockerfile, default Spring Boot port
    # env_file: ./.env  # Uncomment if .env file exists
    # Add depends_on here if you add external services (e.g., databases)
    networks:
      - appnet

# No external services (databases, caches, etc.) detected in project files or structure.
# If your application requires a database or other service, add it below.

networks:
  appnet:
    driver: bridge
